== General Notes

* Make sure to <<setup,initially set-up your environment>>.
* Use the command `help` to get a list of all commands in the release tools.
* After fixing a problem use `workspace cleanup` to clean-up any mess left behind by the previous step.

== The release process

The <<pre-release,*Pre-Release tasks*>> and <<post-release,*Post-Release tasks*>> phases of making a release (opening tickets/closing tickets) is still done manually.

The <<build,*Build and publish the release*>> phase is what's covered by the CI server.

[[pre-release]]
=== 🍃 Pre-Release tasks

. Ensure all work on CVEs potentially contained in the release is done (incl. backports etc.).
. Upgrade dependencies in Spring Data Build parent pom (mind minor/major version rules).
. All release tickets are present (CLI: `$ tracker releasetickets $trainIteration`)
. Review open tickets for release.
. Self-assign release tickets  (CLI: `$ tracker prepare $trainIteration`)
. Announce release preparations to mailing list (https://groups.google.com/forum/#!forum/spring-data-dev)
. 🚥 Continue with `Build and publish the release`

[[prepare-release]]
=== 🥣 Prepare the release

This is the process that checks out the source code and applies a release train tag, in turn tagging all the modules.
This can be done as a CI job, but can also be done locally if need be.
In the event of CI or local failure, we must be and revert each module and delete the related tag.

[%header,cols="1,1"]
|===
|Action
|Command

|Check out this repository from GitHub
|`$ git clone git@github.com:spring-projects/spring-data-release.git`

|Checkout the `main` branch
|`$ git checkout main`

|Edit `ci/release.properties` and assign the version number of the release train you wish to release to `release.version`. (Make sure it's NOT commented out!)
|

|Commit the change to this repository (but don't push to GitHub!)
|`$ git add ci/release.properties && git commit`

|Switch to the `prepare-release` branch
|`$ git checkout prepare-release`

|Set the `HEAD` to `main` to point the content to what is on `main`
|`$ git reset --hard main`

|🚨 *To trigger 🛣 the preparation of the release* `git push` the `prepare-release` branch
|`$ git push origin prepare-release`

|Go to https://jenkins.spring.io/view/SpringData/job/spring-data-release-prepare-release/, Navigate to the `prepare-release` branch.
A job should have started. Click on the active job, and then click on *Open Blue Ocean*.
| Monitor the release preparation process.

|===

After preparing and building (approx. 20 minutes), the Jenkins pipeline will pause, indicating it's time to inspect the logs and make sure the tag was created properl, and put up a prompt: *Proceed* or *Abort*.

🚨 If you click on *Proceed*, then it will continue on to the `github push` phase.


NOTE: If the release preparation goes wrong in any, you'll have to manually clean up any commits, branches, and tags on GitHub.
If it failed BEFORE reaching `github push`, and you *Abort*, then no cleanup required.
You can assess the situation and potentially switch to manual procedure, as shown below.

If something fails on CI, it's possible to carry out this phase manually.

* You MUST have a properly configured local environment.
* You need the tag of the release train you are making.
(This is NOT the tag of an individual module.)
This will be referred to as *{VERSION}* in the following steps.
* If there are partial commits, branches, or tags pushed to GitHub, you'll have to clean them up before carrying out the following procedure.

Assuming things are ready to go, here are the manual steps to prepare a release:

. `mvn clean package -B -DskipTests && java -jar target/spring-data-release-cli.jar`
. `workspace cleanup`
. `verify github`
. `release prepare *{VERSION}*`
. `release conclude *{VERSION}*`

At this point, all the commits are made and the tag has been created and applied.
But it's all local.
You can *still back out* with no cleanup effort. (`workspace cleanup` is all it takes to throw away any release preparation.)

[start=6]
. `github push {VERSION}`

WARNING: If this last step goes wrong in any way, you'll have to manually clean up any commits, branches, and tags on GitHub.

* 🚥 Continue with `Build and publish the release` tasks.

[[build]]
=== 🌿 Build and publish the release

This is the process that checks out a release train tag, builds it, and stages it on Maven Central or Artifactory.

NOTE: If the following CI job fails, and you clean up any potentially staged artifacts on Maven Central/Artifactory, you can repeat the CI job.

If you just completed the <<prepare-release,Prepare the Release step>>, you can skip the following steps that involve updating `ci/release.properties`.

[%header,cols="1,1"]
|===
|Action
|Command

|Check out this repository from GitHub
|`$ git clone git@github.com:spring-projects/spring-data-release.git`

|Checkout the `main` branch
|`$ git checkout main`

|Inspect `ci/release.properties` and make sure it has the target version applied to `release.properties`.
WARNING: If not, *Prepare the Release* may not have been completed properly!
|NA
|===

The following steps will trigger the actual Build and Publish Release CI job.

IMPORTANT: The following steps assume that `ci/release.properties` has `release.version` configured with your release train tag.
If not, then you must back up to the beginning of this section to point it at the right tag.
If that tag has NOT YET BEEN CREATED, then you need to backup to the <<prepare-release,Prepare Release>> section and complete that first.

[%header,cols="1,1"]
|===
|Action
|Command

|Switch to the `release` branch
|`$ git checkout release`

|Set the `HEAD` to `main` to point the content to what is on `main`
|`$ git reset --hard main`

|🚨 *To trigger 🛣 the release* `git push` the `release` branch
|`$ git push origin release`

|Go to https://jenkins.spring.io/view/SpringData/job/spring-data-release-actual-release/, Navigate to the `release` branch.
A job should have started. Click on the active job, and then click on *Open Blue Ocean*.
| Monitor the release process.

|===

After preparing and building (approx. 20 minutes), the Jenkins pipeline will finish with the artifacts staged on either Maven Central or Artifactory.

* For a Maven central release, go to https://s01.oss.sonatype.org/ and login.
** After logging in, you will find a closed Spring Data Release repository.
** Click the repository and then choose "Release".
* For an artifactory release, the release will already have been staged and promoted, so there is nothing more to do.
* 🚥 Continue with `Post-release tasks`

*Background*
====
The release process now has two key phases: *release train tag creation* following by *release train tag build/publish*.
Once a release tag has been created and published to GitHub, it's possible to do the second phase over and over until properly completed.
If this involves Artifactory, you'l have to clean up between attempts.
If this invovles Maven Central, all you have to do is drop the release and start over.

* For a maven central release, you can visit https://s01.oss.sonatype.org/, login, and inspect the staged Spring Data Release. All the Spring Data modules will inside one repository.
* For a milestone/RC release, you can visit https://repo.spring.io/. All the Spring Data modules will be there, each module a separate "build".

For milestone/RC releases, Spring Data Release tools automatically promotes them in Artifactory, so if you have to delete a build, you'll ALSO have to go and delete each module individually.
====

[[post-release]]
=== 🍀 Post-Release tasks

[%header,cols="1,1"]
|===
|Action
|Command

| Finally, push the commit that changed `release.properties` to `main`
| `$ git push origin main` (where you've checked out `spring-data-release`)

|Close release tickets.
|`$ tracker close $trainIteration`

|Create new release versions and tickets for upcoming version
|`$ tracker setup-next $trainIteration.next`

|Update versions in Sagan. `$targets` is given as comma separated lists of code names, without spaces. E.g. `Moore,Neumann`
|`$ sagan update $releasetrains`

|Create list of docs for release announcements
|`$ announcement $trainIteration`

|Announce release (Blog, Twitter) and notify downstream dependency projects as needed.
|N.A.
|===

Congratulations 🥳 You completed the release ❤️.

=== Appendix

[[setup]]
==== One Time Setup

===== Infrastructure requirements

* Ensure you have the credentials for `buildmaster` accounts on https://repo.spring.io.
* Ensure you have the credentials for https://oss.sonatype.org (to deploy and promote GA and service releases, need deployment permissions for `org.springframework.data`) in `settings.xml` for server with id `sonatype`.

Both are available in the Spring/Pivotal Last Pass repository.

===== Prepare local configuration and credentials

Add an `application-local.properties` to the project root and add the following properties:

* `git.username` - Your GitHub username.
* `git.password` - Your GitHub Password (or API key with scopes: `public_repo, read:org, repo:status, repo_deployment, user` when using 2FA).
* `git.author` - Your full name (used for preparing commits).
* `git.email` - Your email (used for preparing commits).
* `maven.mavenHome` - Pointing to the location of your Maven installation.
* `deployment.username` - Your Artifactory user.
* `deployment.api-key` - The Artifactory API key to use for artifact promotion.
* `deployment.password` - The encrypted Artifactory password..
* `gpg.keyname` - The GPG key name.
* `gpg.passphrase` - The password of your GPG key.
* `gpg.executable` - Path to your GPG executable, typically `/usr/local/MacGPG2/bin/gpg2`
 or `/usr/local/bin/gpg`.
* `sagan.key` - Sagan authentication token. Must be a valid GitHub token. Can be the same
 as `git.password` when using a GitHub token as password.

After that, run the `verify` command (`$ verify`) to verify your settings (authentication,
correct Maven, Java, and GPG setup).

See `application-local.template` for details.

==== Detailed commands performed by `spring-data-release-cli`

|===
|Action |Command

|All release tickets are present |`$ tracker releasetickets $trainIteration`
|Self-assign release tickets |`$ tracker prepare $trainIteration`
2+| *Release the binaries*
| |`$ release prepare $trainIteration`
|Build the artefacts and push them to the appropriate maven repository |`$ release build $trainIteration`
| |`$ release conclude $trainIteration`
|Push the created commits to GitHub |`$ github push $trainIteration`
|Push new maintenance branches if the release version was a GA release (`X.Y.0` version) |`$ git push $trainIteration.next`
|Distribute documentation and static resources from tag |`$ release distribute $trainIteration`
2+| *Post-release tasks*
|Close JIRA tickets and GitHub release tickets. |`$ tracker close $trainIteration`
|Create new release versions and tickets for upcoming version |`$ tracker setup-next $trainIteration.next`
|Update versions in Sagan. `$targets` is given as comma separated lists of code names, without spaces. E.g. `Moore,Neumann` |`$ sagan update $releasetrains`
|Create list of docs for release announcements |`$ announcement $trainIteration`
|===

==== Utilities

===== GitHub Labels

`ProjectLabelConfiguration` contains a per-project configuration which labels should be present in a project. To apply that configuration (create or update), use:

----
$ github update labels $project
----

===== Dependency Upgrade

`ProjectDependencies` contains a per-project configuration of dependencies.

Workflow:

* Check for dependency upgrades `$ dependency check $trainIteration`

Reports upgradable dependencies for Build and Modules and
creates `dependency-upgrade-build.properties` file.
Edit `dependency-upgrade-build.properties` to specify the dependency version to upgrade.
Removing a line will omit that dependency upgrade.

* Apply dependency upgrade with `$ dependency upgrade $trainIteration`. Applies dependency
 upgrades currently only to Spring Data Build.
* Report store-specific dependencies to Spring Boot's current upgrade
 ticket (https://github.com/spring-projects/spring-boot/issues/24036[sample]) `$ dependency report $trainIteration`

===== CI Properties Distribution

To distribute `ci/pipeline.properties` across all modules use:

`$ infra distribute ci-properties $trainIteration`
